name: dart_koans
version: 0.0.2+2
author: Matthew Butler
description: An application designed to help teach basics of the Dart language and core libraries through Unittests. It is highly recommended that this package is downloaded manually or cloning the github repository. *Do not* install with pub.
homepage: https://github.com/butlermatt/dart_koans
environment:
  sdk: '>=1.3.0 <1.7.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
  unittest: '>=0.10.0 <0.12.0'
